Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Lint/UselessAssignment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Metrics/MethodLength:
  Max: 1000